spring.application.name=user-service

server.port = 9020

jwt.secretKey = sodjkbv398g793gfbu234bc743fbuewbcj382938ry4848757@@*##^$&%#^*^@(*

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=postgres
spring.datasource.password=Nayeem@2003
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




spring.cloud.compatibility-verifier.enabled=false


server.servlet.context-path=/users

